add format-phone utils
alfa-laboratory/utils pull request #44
Opened 2021-01-19 14:12 UTC by aleksey-ilin

Утилита для форматирования номера телефона.

2021-01-21 07:14 UTC, aso1datov commented on packages/utils/src/format-phone/util.test.ts
> +        expect(getRawPhoneNumber('+7 111 222-33-44')).toBe('71112223344');
Накинь еще кейсы со скобочками

2021-01-21 10:00 UTC, aleksey-ilin commented on packages/utils/src/format-phone/util.test.ts
> +        expect(getRawPhoneNumber('+7 111 222-33-44')).toBe('71112223344');
добавил тестов и немного изменил функцию

2021-01-21 10:07 UTC, AleksandrSerov commented
Хочется, чтобы был такой вариант форматирования: +7 000 000 00 00
Как вариант сделать
formatPhoneNumber(phone: string, format: какой то enum форматов) => string

2021-01-21 10:12 UTC, Makvagabo approved these changes

2021-01-21 10:17 UTC, Makvagabo commented
> Хочется, чтобы был такой вариант форматирования: +7 000 000 00 00
> Как вариант сделать
> formatPhoneNumber(phone: string, format: какой то enum форматов) => string

А зачем? Можно список тех вариантов форматирования которые сейчас используются или будут использоваться?

2021-01-21 10:21 UTC, AleksandrSerov commented
> > Хочется, чтобы был такой вариант форматирования: +7 000 000 00 00
> > Как вариант сделать
> > formatPhoneNumber(phone: string, format: какой то enum форматов) => string
> 
> А зачем? Можно список тех вариантов форматирования которые сейчас используются или будут использоваться?

Такой формат используется здесь
https://github.com/alfa-laboratory/core-components/blob/master/packages/confirmation/src/component.tsx#L58

А для отображения используется еще два формата
+7 111 222-33-44 и 8 800 222-33-44

2021-01-21 12:53 UTC, aleksey-ilin commented
> Хочется, чтобы был такой вариант форматирования: +7 000 000 00 00
> Как вариант сделать
> formatPhoneNumber(phone: string, format: какой то enum форматов) => string

2021-01-21 12:56 UTC, aleksey-ilin commented
> > > Хочется, чтобы был такой вариант форматирования: +7 000 000 00 00
> > > Как вариант сделать
> > > formatPhoneNumber(phone: string, format: какой то enum форматов) => string
> > 
> > 
> > А зачем? Можно список тех вариантов форматирования которые сейчас используются или будут использоваться?
> 
> Такой формат используется здесь
> https://github.com/alfa-laboratory/core-components/blob/master/packages/confirmation/src/component.tsx#L58
> 
> А для отображения используется еще два формата
> +7 111 222-33-44 и 8 800 222-33-44

мне кажется для этого компонента не стоит делать спец формат, а лучше в него передавать неотформатированный номер телефона. [предложил](https://github.com/alfa-laboratory/core-components/issues/481) в `core-components` поменять prop

2021-01-21 12:57 UTC, aleksey-ilin commented
> > Хочется, чтобы был такой вариант форматирования: +7 000 000 00 00
> > Как вариант сделать
> > formatPhoneNumber(phone: string, format: какой то enum форматов) => string
> 
> А зачем? Можно список тех вариантов форматирования которые сейчас используются или будут использоваться?

список есть в [issue](https://github.com/alfa-laboratory/utils/issues/16)

2021-01-22 10:07 UTC, SiebenSieben approved these changes

2021-01-24 21:51 UTC, etroynov requested changes

2021-01-24 21:51 UTC, etroynov commented on packages/utils/src/format-phone/util.ts
> +export const getRawPhoneNumber = (phone: string): string => phone.replace(/\D+/g, '');
эта функция нарушает соглашение один файл === одна экспортируемая функция. Либо ее сделать локальной но тогда смысла от нее нет, либо вынести ее в отдельный файл.

2021-01-24 21:51 UTC, etroynov commented on packages/utils/src/format-phone/util.ts
> +const mask = [
Это не маска это regex паттерн поэтому логичнее переменную назвать pattern.

2021-01-24 21:51 UTC, etroynov commented on packages/utils/src/format-phone/util.ts
> +    const formattedPhone = conformToMask(rawPhone, mask, { guide: false }).conformedValue;
conform не самый подходящий вариант, думаю лучше использовать match как и делает js

2021-01-24 21:51 UTC, etroynov commented on packages/utils/src/format-phone/util.ts
> +export const formatPhoneNumber = (phone: string): string => {
поскольку здесь есть 2 функции то напрашивается мысль что это должен быть namespace:
- phone.number.format();
- phone.number.raw();
или:
- phoneNumber.format();
- phoneNumber.raw();

2021-01-25 08:37 UTC, stepancar commented on yarn.lock
> +>>>>>>> develop
криво по мержено

2021-01-25 09:25 UTC, aleksey-ilin commented on packages/utils/src/format-phone/util.ts
> +const mask = [
удалил переменную

2021-01-25 09:25 UTC, aleksey-ilin commented on packages/utils/src/format-phone/util.ts
> +    const formattedPhone = conformToMask(rawPhone, mask, { guide: false }).conformedValue;
переделал на `replace` с регуляркой

2021-01-25 09:26 UTC, aleksey-ilin commented on packages/utils/src/format-phone/util.ts
> +export const formatPhoneNumber = (phone: string): string => {
добавил `namespace`

2021-01-25 09:26 UTC, aleksey-ilin commented on packages/utils/src/format-phone/util.ts
> +export const getRawPhoneNumber = (phone: string): string => phone.replace(/\D+/g, '');
добавил `namespace`

2021-01-25 09:29 UTC, aleksey-ilin commented on yarn.lock
> +>>>>>>> develop
починил

2021-01-25 13:31 UTC, Luchanso approved these changes

2021-01-25 13:33 UTC, etroynov commented on packages/utils/src/format-phone/util.ts
> +const getRawPhoneNumber = (phone: string): string => phone.replace(/\D+/g, '');
что бы не нарушать целостность подхода рекомендую вынести это в отдельную папку:
-format-phone
--get-raw
--- util.ts
--- util.test.ts
--- index.ts
--format
--- util.ts
--- util.test.ts
--- index.ts
--index.ts - тут реэкспорт

2021-01-25 14:39 UTC, aleksey-ilin commented on packages/utils/src/format-phone/util.ts
> +const getRawPhoneNumber = (phone: string): string => phone.replace(/\D+/g, '');
сделал по твоей рекомендации

2021-01-26 12:29 UTC, aso1datov approved these changes

2021-01-26 23:31 UTC, stepancar approved these changes

2021-01-27 06:31 UTC, AleksandrSerov approved these changes

2021-01-27 08:14 UTC, etroynov approved these changes

2021-01-27 08:15 UTC, merged