feat(use-force-update): add hook
alfa-laboratory/utils pull request #77
Opened 2021-12-27 10:30 UTC by koretskyhub

в новом клике уже целый ряд мест где без этого хука никак, поэтому хотели перенести хук в 1 место

оригинальный код https://github.com/CharlesStover/use-force-update

2021-12-27 13:17 UTC, reabiliti commented on packages/hooks/src/useForceUpdate/hook.ts
> +export default function useForceUpdate(): () => void {
Может стоит удалить default, в других хуках не используется импорт по умочанию

2021-12-27 14:55 UTC, koretskyhub commented on packages/hooks/src/useForceUpdate/hook.ts
> +export default function useForceUpdate(): () => void {
👍

2021-12-27 21:36 UTC, reme3d2y requested changes
Надо отформатировать по нашим конфигам и можно убрать лишние аннотации, типа () => void и т.д

2021-12-28 07:06 UTC, koretskyhub commented
> Надо отформатировать по нашим конфигам и можно убрать лишние аннотации, типа () => void и т.д

странно что на прекомит не форматируется автоматом

2021-12-28 09:31 UTC, reabiliti approved these changes

2021-12-29 16:24 UTC, reme3d2y approved these changes

2021-12-29 16:24 UTC, merged