fix(): CNY unicode
alfa-laboratory/utils pull request #92
Opened 2022-04-05 09:36 UTC by MalSolt

Changed yuan(CNY) unicode

2022-04-05 09:45 UTC, aleksey-ilin approved these changes

2022-04-05 09:48 UTC, Makvagabo approved these changes

2022-04-05 10:11 UTC, NatalyaZ approved these changes

2022-04-05 11:49 UTC, stepancar commented
Ждем апрув от продакта

2022-04-05 12:25 UTC, SiebenSieben commented
Ждём апрув от корпоратов

2022-04-05 14:35 UTC, reabiliti approved these changes

2022-04-06 07:11 UTC, SiebenSieben requested changes
Корпораты блочат такое изменение, можно добавить какой-то кастомный символ (CNYALT, например)

2022-04-06 08:32 UTC, closed without merging